### PR TITLE
Add publish workflow, update version and dependencies

### LINKED ISSUE #5: Publish cargo and remove auto-generated bindings

### PR DESCRIPTION
**Pull request by shuhuiluo**
Closes #5.
Add [`CARGO_REGISTRY_TOKEN`](https://doc.rust-lang.org/cargo/reference/config.html?highlight=CARGO_REGISTRY_TOKEN#credentials) to repo secrets before release.

### CODE REVIEW

**Review by gnarlycow — APPROVED** [review]
Thanks!

**Comment by gnarlycow** [comment]
Do you know why the CI hardhat test is trying to connect to Infura even if you seem to have changed it to viem's default mainnet endpoint which is cloudflare-eth.com?

**Comment by shuhuiluo** [comment]
> Do you know why the CI hardhat test is trying to connect to Infura even if you seem to have changed it to viem's default mainnet endpoint which is cloudflare-eth.com?

I didn't change the RPC for hardhat tests. Please merge it since I don't have write access.

**Comment by shuhuiluo** [comment]
@gnarlycow Please merge it and publish to crates.io.

**Pull request merged**
